language: erlang
otp_release:
  - 19.3.6.1
before_install:
  - ./ci before_install "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
install:
  - ./ci install "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
script:
  - ./ci script "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
after_failure:
  - ./ci after_failure "${JOB:?}" "${TRAVIS_BUILD_DIR:?}"
matrix:
  allow_failures:
    - env: JOB=unit-tests
    - env: JOB=dialyzer
    - env: JOB=xref
  fast_finish: true
env:
  - JOB=tests
  - JOB=unit-tests
  - JOB=dialyzer
  - JOB=xref
cache:
  directories:
    - .plt
