swagger: '2.0'
info:
  description: 'This is the [Aeternity](https://www.aeternity.com/) Testnet API.'
  version: 1.0.0
  title: Aeternity Testnet
  termsOfService: 'https://www.aeternity.com/terms/'
  contact:
    email: apiteam@aeternity.com
basePath: /v1
tags:
  - name: external
    description: External API
  - name: internal
    description: Internal API
schemes:
  - http
paths:
  /create-account:
    post:
      tags:
        - internal
      operationId: AddAccount
      summary: Add a new account
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Account object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/CreateAccount'
      responses:
        '405':
          description: Invalid input
      security: []
  /delete-account:
    post:
      tags:
        - internal
      operationId: DeleteAccount
      summary: Delete account
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Pubkey of the account to be deleted
          required: true
          schema:
            $ref: '#/definitions/PubKey'
      responses:
        '405':
          description: Invalid input
      security: []
  /repo-account:
    post:
      tags:
        - internal
      operationId: RepoAccount
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Pubkey of the account
          required: true
          schema:
            $ref: '#/definitions/PubKey'
      responses:
        '405':
          description: Invalid input
      security: []
  /fetch-account:
    post:
      tags:
        - internal
      operationId: FetchAccount
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Pubkey of the account
          required: true
          schema:
            $ref: '#/definitions/PubKey'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Account'
        '405':
          description: Invalid input
        '404':
          description: Not found
      security: []
  /top:
    get:
      tags:
        - internal
      operationId: GetTop
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Top'
      security: []
  /create-keypair:
    get:
      tags:
        - internal
      operationId: CreateKeyPair
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/KeyPair'
      security: []
  /set-keypair:
    post:
      tags:
        - internal
      operationId: SetKeyPair
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/SetKeyPair'
      responses:
        '405':
          description: Invalid input
      security: []
  /fetch-pubkey:
    get:
      tags:
        - internal
      operationId: FetchPubKey
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PubKey'
      security: []
  /peer:
    post:
      tags:
        - internal
      operationId: AddPeer
      summary: Add a new peer
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Peer object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Peer'
      responses:
        '405':
          description: Invalid input
      security: []
  /new-channel-with-server:
    post:
      tags:
        - internal
      operationId: NewChannelWithServer
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/NewChannelWithServer'
      responses:
        '405':
          description: Invalid input
      security: []
  /spend:
    post:
      tags:
        - internal
      operationId: Spend
      summary: Spend
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Spend object
          required: true
          schema:
            $ref: '#/definitions/Spend'
      responses:
        '405':
          description: Invalid input
      security: []
  /channel-spend:
    post:
      tags:
        - internal
      operationId: ChannelSpend
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/ChannelSpend'
      responses:
        '405':
          description: Invalid input
      security: []
  /lightning-spend:
    post:
      tags:
        - internal
      operationId: LightningSpend
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/LightningSpend'
      responses:
        '405':
          description: Invalid input
      security: []
  /pull-channel-state:
    post:
      tags:
        - internal
      operationId: PullChannelState
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/PullChannelState'
      responses:
        '405':
          description: Invalid input
      security: []
  /sync:
    post:
      tags:
        - internal
      summary: Sync with a node
      description: ''
      operationId: Sync
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Sync parameters that needs to be sent
          required: true
          schema:
            $ref: '#/definitions/Sync'
      responses:
        '405':
          description: Invalid input
      security: []
  /mine_block:
    post:
      tags:
        - internal
      summary: Mine blocks on a node
      description: ''
      operationId: MineBlock
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Mine blocks parameters that needs to be sent
          required: true
          schema:
            $ref: '#/definitions/MineBlock'
      responses:
        '405':
          description: Invalid input
      security: []
  /header/{block_id}:
    get:
      tags:
        - external
      operationId: GetHeader
      produces:
        - application/json
      parameters:
        - in: path
          name: block_id
          description: Block number
          required: true
          allowMultiple: false
          type: integer
          format: int16
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Header'
      security: []
  /headers:
    get:
      tags:
        - external
      operationId: GetHeaders
      produces:
        - application/json
      parameters:
        - name: block_ids
          in: query
          type: string
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Headers'
      security: []
definitions:
  CreateAccount:
    type: object
    properties:
      pubkey:
        type: string
      amount:
        type: integer
        format: int64
  Top:
    type: object
    properties:
      hash:
        type: string
      height:
        type: integer
        format: int64
  KeyPair:
    type: object
    properties:
      public:
        type: string
      private:
        type: string
  SetKeyPair:
    type: object
    properties:
      public:
        type: string
      private:
        type: string
      brain-wallet:
        type: string
  Peer:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
  Spend:
    type: object
    properties:
      pubkey:
        type: string
      amount:
        type: integer
        format: int64
  NewChannelWithServer:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
      channel-id:
        type: integer
        format: int64
      balance:
        type: integer
        format: int64
      receive-limit:
        type: integer
        format: int64
      fee:
        type: integer
        format: int64
      delay:
        type: integer
        format: int64
  ChannelSpend:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
      amount:
        type: integer
        format: int64
  LightningSpend:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
      pubkey:
        type: string
      amount:
        type: integer
        format: int64
      fee:
        type: integer
        format: int64
  PullChannelState:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
  Sync:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int64
  MineBlock:
    type: object
    properties:
      count:
        type: integer
        format: int64
      times:
        type: integer
        format: int64
  Headers:
    type: array
    items:
      $ref: '#/definitions/Header'
  Header:
    type: object
    properties:
      block_id:
        type: integer
        format: int64
      block_header:
        type: string
  PubKey:
    type: object
    properties:
      pubkey:
        type: string
  Account:
    type: object
    properties:
      pubkey:
        type: string
      balance:
        type: integer
        format: int64
      nonce:
        type: integer
        format: int64
      height:
        type: integer
        format: int64
      bets:
        type: integer
        format: int64
      shares:
        type: integer
        format: int64
externalDocs:
  description: Find out more about Aeternity
  url: 'http://www.aeternity.com'
